### ISSUE TITLE
feat: Kakarot Sequencer

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/ef-tests#101]
# Feature Request

Set-up a Kakarot sequencer for the execution of the ethereum tests.

**Describe the Feature Request**

In order to improve the current speed of the tests, have more control and spend time digging in blockifier and cairo-rs instead of working on Katana, Madara or another sequencer, we will implement our own mini sequencer for the ef-tests. Depending on the demand, this sequencer could be extended in order to facilitate testing of the RPC or of the Kakarot repo itself. For now however, we will limit the scope to the ethereum tests.

**Describe Preferred Solution**

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/ef-tests/issues/103
- [ ] https://github.com/kkrt-labs/ef-tests/issues/106
- [ ] https://github.com/kkrt-labs/ef-tests/issues/143
- [ ] https://github.com/kkrt-labs/ef-tests/issues/267
- [ ] Add light testing. For now we can probably just run a couple of ef-tests on it as regression testing.
- [ ] https://github.com/kkrt-labs/ef-tests/issues/102
```

**Comment by jobez** [comment]
is the idea that this exists in ef-tests first, then later we move it into the refactored `kakarot-sdk`?

**Comment by greged93** [comment]
I'm not too sure, I think it should probably exist in the ef-tests for as long as its scope is limited to ef-tests. If one day we want to extend its use to Python tests for Kakarot or RPC, then indeed we can move it to `kakarot-sdk`.

**Comment by bajpai244** [comment]
> I think it should probably exist in the ef-tests for as long as its scope is limited to ef-tests. If one day we want to extend its use to Python tests for Kakarot or RPC, then indeed we can move it to `kakarot-sdk`.

@greged93 I agree on this as well.

**Comment by ClementWalter** [comment]
also, it seems like 100x times easier to just make a simple sequencer for the ef tests than implementing the whole RPC interface

**Comment by ClementWalter** [comment]
and for RPC, if we stick to RPC high level for end to end tests, there is already katana and soon starknet-devnet-rs, one using blockifier and the other starknet_in_rust, so let's wait on this side

**Comment by greged93** [comment]
I agree, the idea for now is to have something without any RPC and just a very easy API
