### ISSUE TITLE
docs: add rustdocumentation /// style for some utils function 

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/ef-tests#16]
```[tasklist]
### Tasks
- [ ] Go through utils
- [ ] Those that'll be refactored into smaller utils function, you can skip for now
- [ ] The functions that are the right size, add rust doc on it
``` 

Motivation: ef-tests are very complicated! And we need to do a decent amount of tinkering.
Always nice to explain our tinkering, why it's necessary
Don't hesitate to do verbose!!
