### ISSUE TITLE
epic: add `stMemoryTests`

### ISSUE THREAD

**Issue by bajpai244** [kkrt-labs/ef-tests#26]
add [stMemoryTest](https://github.com/ethereum/tests/tree/develop/GeneralStateTests/stMemoryTest) to the runner.

- Add stMemoryTest [here](https://github.com/kkrt-labs/ef-tests/blob/c295d34b008ae0f190ba8163874bf5f4025ed6c6/crates/ef-testing/tests/tests.rs#L31).

**When do we consider this epic complete?**

When we have all relevant tests working from the [stMemoryTest](https://github.com/ethereum/tests/tree/develop/GeneralStateTests/stMemoryTest) directory.

#### Current state of the test

```shell
Ran 71 tests (67 passed, 4 failed, 0 skipped)
[!] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/buffer.json failed (description: buffer): Test failed: failed test buffer_d100g0v0_Shanghai: expected storage value 0x00000000000000000000000000000000000000000000000000000000000060a7, got 0x0000000000000000000000000000000000000000000000000000000000000000
[!] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/bufferSrcOffset.json failed (description: bufferSrcOffset): Test failed: failed test bufferSrcOffset_d102g0v0_Shanghai: expected storage value 0x00000000000000000000000000000000000000000000000000000000000060a7, got 0x0000000000000000000000000000000000000000000000000000000000000000
[!] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/memCopySelf.json failed (description: memCopySelf): Test failed: failed test memCopySelf_d0g0v0_Shanghai: expected storage value 0x0000000000000000000000000000000000000000000000000000000000000000, got 0x00000000000000000000000000000000000000000000000000000000000060a7
[!] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/oog.json failed (description: oog): Test failed: Transaction hash not found
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem64kb_singleByte-32.json passed (description: mem64kb_singleByte-32)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mload8bitBound.json passed (description: mload8bitBound)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/stackLimitPush32_1025.json passed (description: stackLimitPush32_1025)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/log2_dejavu.json passed (description: log2_dejavu)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/codecopy_dejavu.json passed (description: codecopy_dejavu)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem64kb-32.json passed (description: mem64kb-32)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem32kb_singleByte-33.json passed (description: mem32kb_singleByte-33)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mstroe8_dejavu.json passed (description: mstroe8_dejavu)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/codecopy_dejavu2.json passed (description: codecopy_dejavu2)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/sha3_dejavu.json passed (description: sha3_dejavu)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem32kb-32.json passed (description: mem32kb-32)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem64kb+1.json passed (description: mem64kb+1)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem32kb.json passed (description: mem32kb)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem32kb-33.json passed (description: mem32kb-33)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem64kb-33.json passed (description: mem64kb-33)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem32kb_singleByte-32.json passed (description: mem32kb_singleByte-32)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/stackLimitPush32_1024.json passed (description: stackLimitPush32_1024)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem64kb-1.json passed (description: mem64kb-1)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/stackLimitGas_1023.json passed (description: stackLimitGas_1023)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem64kb_singleByte-33.json passed (description: mem64kb_singleByte-33)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/log4_dejavu.json passed (description: log4_dejavu)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem64kb_singleByte.json passed (description: mem64kb_singleByte)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/callDataCopyOffset.json passed (description: callDataCopyOffset)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem64kb_singleByte+1.json passed (description: mem64kb_singleByte+1)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/calldatacopy_dejavu2.json passed (description: calldatacopy_dejavu2)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem32kb+32.json passed (description: mem32kb+32)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem64kb+32.json passed (description: mem64kb+32)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem32kb_singleByte+33.json passed (description: mem32kb_singleByte+33)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/stackLimitGas_1024.json passed (description: stackLimitGas_1024)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/stackLimitPush32_1023.json passed (description: stackLimitPush32_1023)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem32kb_singleByte-1.json passed (description: mem32kb_singleByte-1)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem64kb_singleByte+32.json passed (description: mem64kb_singleByte+32)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem64kb_singleByte+33.json passed (description: mem64kb_singleByte+33)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem64kb_singleByte-1.json passed (description: mem64kb_singleByte-1)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem31b_singleByte.json passed (description: mem31b_singleByte)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/stackLimitGas_1025.json passed (description: stackLimitGas_1025)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem64kb+33.json passed (description: mem64kb+33)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem32kb_singleByte+32.json passed (description: mem32kb_singleByte+32)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem32kb+33.json passed (description: mem32kb+33)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem32kb_singleByte.json passed (description: mem32kb_singleByte)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/log1_dejavu.json passed (description: log1_dejavu)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem32kb_singleByte+1.json passed (description: mem32kb_singleByte+1)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mload_dejavu.json passed (description: mload_dejavu)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem64kb.json passed (description: mem64kb)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mload16bitBound.json passed (description: mload16bitBound)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/memReturn.json passed (description: memReturn)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem0b_singleByte.json passed (description: mem0b_singleByte)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem32kb+1.json passed (description: mem32kb+1)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/stackLimitPush31_1023.json passed (description: stackLimitPush31_1023)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem32kb_singleByte+31.json passed (description: mem32kb_singleByte+31)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem64kb+31.json passed (description: mem64kb+31)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem64kb_singleByte+31.json passed (description: mem64kb_singleByte+31)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/log3_dejavu.json passed (description: log3_dejavu)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem32b_singleByte.json passed (description: mem32b_singleByte)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem32kb-1.json passed (description: mem32kb-1)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem32kb+31.json passed (description: mem32kb+31)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem32kb_singleByte-31.json passed (description: mem32kb_singleByte-31)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/stackLimitPush31_1025.json passed (description: stackLimitPush31_1025)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem32kb-31.json passed (description: mem32kb-31)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/codeCopyOffset.json passed (description: codeCopyOffset)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/extcodecopy_dejavu.json passed (description: extcodecopy_dejavu)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem64kb_singleByte-31.json passed (description: mem64kb_singleByte-31)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem33b_singleByte.json passed (description: mem33b_singleByte)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/stackLimitPush31_1024.json passed (description: stackLimitPush31_1024)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/calldatacopy_dejavu.json passed (description: calldatacopy_dejavu)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mem64kb-31.json passed (description: mem64kb-31)
[✅] Case /Users/harshbajpai/Desktop/Projects/ef-tests/crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/stMemoryTest/mstore_dejavu.json passed (description: mstore_dejavu)
```
```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/ef-tests/issues/40
- [ ] https://github.com/kkrt-labs/ef-tests/issues/49
- [ ] https://github.com/kkrt-labs/ef-tests/issues/50
- [ ] https://github.com/kkrt-labs/ef-tests/issues/51
- [ ] https://github.com/kkrt-labs/ef-tests/issues/52
```
