### ISSUE TITLE
epic: add `VMTests`

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/ef-tests#28]
Add all `VMTests` (or justify the skipped ones) as a suite of tests

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/ef-tests/issues/20
- [ ] https://github.com/kkrt-labs/ef-tests/issues/19
- [ ] https://github.com/kkrt-labs/kakarot/issues/700
- [ ] https://github.com/kkrt-labs/kakarot/issues/695
- [ ] https://github.com/kkrt-labs/kakarot/issues/694
- [ ] https://github.com/kkrt-labs/kakarot/issues/693
- [ ] https://github.com/kkrt-labs/kakarot/issues/677
- [ ] https://github.com/kkrt-labs/ef-tests/issues/31
- [ ] https://github.com/kkrt-labs/ef-tests/issues/36
- [ ] https://github.com/kkrt-labs/ef-tests/issues/38
- [ ] https://github.com/kkrt-labs/ef-tests/issues/39
- [ ] https://github.com/kkrt-labs/ef-tests/issues/57
- [ ] https://github.com/kkrt-labs/ef-tests/issues/61
- [ ] https://github.com/kkrt-labs/ef-tests/issues/63
- [ ] https://github.com/kkrt-labs/ef-tests/issues/67
```
