### ISSUE TITLE
bug: mismatch expected nonce in collision tests

### ISSUE THREAD

**Issue by ftupas** [kkrt-labs/ef-tests#33]
# Bug Report

**Kakarot version:** https://github.com/kkrt-labs/kakarot/commit/0c6e7a62a38e973ad6ceebfbf648841749ffe0ee

**Current behavior:** 
Tests for SSTORE provided by ethereum/tests fails during the following tests when transactions are expected to pass 

Test Name | Actual | Expected
-- | -- | --
InitCollision_d0g0v0_Shanghai | 0x0000000000000000000000000000000000000000000000000000000000000000 | 0x0000000000000000000000000000000000000000000000000000000000000001
InitCollisionNonZeroNonce_d0g0v0_Shanghai | 0x0000000000000000000000000000000000000000000000000000000000000000 | 0x0000000000000000000000000000000000000000000000000000000000000001

Instead they are all failing with mismatch on expected nonce

**Expected behavior:**
Test should pass.

**Steps to reproduce:**

- clone ef-tests: https://github.com/kkrt-labs/ef-tests
- generate katana dump of kakarot system and move the .katana folder to your ef-tests directory
- run the following

```shell
make setup
make target=InitCollision_d0g0v0_Shanghai ef-test
```

Failing output should be:
```Python
Test failed: failed test InitCollision_d0g0v0_Shanghai: expected nonce 0x0000000000000000000000000000000000000000000000000000000000000001, got 0x0000000000000000000000000000000000000000000000000000000000000000
```
```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/ef-tests/issues/41
- [ ] https://github.com/kkrt-labs/kakarot/issues/715
- [ ] https://github.com/kkrt-labs/kakarot-rpc/issues/502
- [ ] https://github.com/kkrt-labs/ef-tests/issues/45
```

**Comment by ftupas** [comment]
With @ClementWalter , we have done the following

- realize that this [tx](https://github.com/ethereum/tests/blob/develop/BlockchainTests/GeneralStateTests/stSStoreTest/InitCollision.json#L610-L621) is a create tx
- use this [util](https://github.com/kkrt-labs/kakarot/blob/95df46cf88a4225d26e7a642fe2d149b41c55249/tests/utils/helpers.py#L79) to compute the target address
- confirmed resulting address is `0x6295ee1b4f6dd65047762f924ecd367c17eabf8f` 
- this is a [pre-deployed](https://github.com/ethereum/tests/blob/develop/BlockchainTests/GeneralStateTests/stSStoreTest/InitCollision.json#L684) contract account
- contract account nonce are not stored in the sequencer nonce storage
- we need to check the  managed [nonce](https://github.com/kkrt-labs/kakarot/blob/c04cb72f040e059dfa3a8dc4ca24c6a68083409b/src/kakarot/accounts/library.cairo#L25) instead

Another problem
- we realize that this has been pre-deployed as an eoa instead of a contract account, see [here](https://github.com/kkrt-labs/ef-tests/blob/8d64b0a14b68b5dd5e14ada8e8700b692967e132/crates/ef-testing/src/storage/mod.rs#L84-L89)
- we need to fix how we handle the pre-state for the accounts

Next steps

In [handle_post_state](https://github.com/kkrt-labs/ef-tests/blob/a98f476f526ea71ffe08074fa6f83719edd40e8a/crates/ef-testing/src/models/case.rs#L127):
- if the account we are asserting against is an EOA, we use protocol-level nonce
- if it's a contract account, we use the managed nonce

In [write_test_state](https://github.com/kkrt-labs/ef-tests/blob/8d64b0a14b68b5dd5e14ada8e8700b692967e132/crates/ef-testing/src/storage/mod.rs#L54):
- Check if the account has storage as well, not just code
- Update these [lines](https://github.com/kkrt-labs/ef-tests/blob/8d64b0a14b68b5dd5e14ada8e8700b692967e132/crates/ef-testing/src/storage/mod.rs#L84-L90) to include this logic

Appendix
- [Types of Account](https://ethereum.org/en/developers/docs/accounts/#types-of-account)
