### ISSUE TITLE
epic: add `stMemExpandingEIP150Calls` testsuite to the blockchain_tests module 

### ISSUE THREAD

**Issue by khaeljy** [kkrt-labs/ef-tests#348]
# Feature Request

**Describe the Feature Request**

Inside the BlockchainTests > GeneralStateTests, integrate `stMemExpandingEIP150Calls` to the test suite.
```[tasklist]
### Tasks
- [x] uncomment the test suite in: https://github.com/kkrt-labs/ef-tests/blob/b1720e2b1d926460a63b3333c6e0eaa5d3ba8d51/crates/ef-testing/tests/tests.rs#L62
- [x] Run the ef tests `make ef-tests`
- [x] See which tests are failing if any, create issues for each unique error message which their test linked (include screenshots, code snippets). Refrain from debugging at this point. This is an integration task.
- [x] If some tests fail, add them in https://github.com/kkrt-labs/ef-tests/blob/b1720e2b1d926460a63b3333c6e0eaa5d3ba8d51/blockchain-tests-skip.yml#L1
- [x] you're done
```

```[tasklist]
### Linked debuggor issues
- [ ] https://github.com/kkrt-labs/ef-tests/issues/356
- [ ] https://github.com/kkrt-labs/ef-tests/issues/357
```
