### ISSUE TITLE
dev: pull compiled contracts of Kakarot system from kakarot CI artifacts instead of Git Submodule

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/ef-tests#488]
Currently, we have Kakarot as a git submodule. We use it to compile the contracts.

```[tasklist]
### Tasks
- [x] Create a Script that can grab all the compiled contracts from the CI of Kakarot (artifacts of all compiled contracts are reachable at latest main)
- [x] Use that script to access compiled contracts
- [x] Use these compiled contracts to deploy all the kakarot smart contracts needed for execution on the custom kakarot sequencer
- [x] Delete the git dependency to Kakarot
```

**Comment by khaeljy** [comment]
I'd like to try this, is it possible?

**Comment by Eikix** [comment]
Sure!
