### ISSUE TITLE
bug: balance mismatch in `stRevert`

### ISSUE THREAD

**Issue by ClementWalter** [kkrt-labs/ef-tests#538]
### Current behavior

Upon REVERT, the transferred funds are not reinitialized.

### Expected behavior

Funds transfer should be cancelled.

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
- [ ] Case RevertOpcodeInInit.json
- [ ] Case RevertSubCallStorageOOG.json
- [ ] Case RevertOpcode.json
- [ ] Case RevertOpcodeWithBigOutputInInit.json
- [ ] Case PythonRevertTestTue201814-1430
- [ ] Case RevertSubCallStorageOOG2.json
```
