### ISSUE TITLE
bug: Gas-related issues

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/ef-tests#550]
### Current behavior
Most tests marked `OOG` should fail in the EVM with out of gas. Since Kakarot does not perform correct gas accounting, this is not translated in the result.

```[tasklist]
### Tasks
- [ ] dayLimitConstructionOOG.json
- [ ] walletConstructionOOG.json
- [ ] multiOwnedConstructionNotEnoughGasPartial.json
- [ ] createNameRegistratorPerTxsNotEnoughGas.json
- [ ] logInOOG_Call.json
- [ ] mload32bitBound.json
- [ ] codesizeOOGInvalidSize.json
- [ ] createInitFail_OOGduringInit
- [ ] create2collisionSelfdestructedOOG_d0g0v0
- [ ] create2collisionSelfdestructedOOG_d1g0v0
- [ ] create2collisionSelfdestructedOOG_d2g0v0
- [ ] CallContractToCreateContractOOG_d0g0v0
- [ ] Opcodes_TransactionInit_d111g0v0_Shanghai
- [ ] static_InternalCallHittingGasLimit_d0g0v0_Shanghai
- [ ] static_InternalCallHittingGasLimit2_d0g0v0_Shanghai
- [ ] invalidTr_d0g0v0_Shanghai
- [ ] ContractStoreClearsOOG.json
- [ ] InternlCallStoreClearsOOG.json
- [ ] StoreClearsAndInternlCallStoreClearsOOG.json
```

**Comment by enitrat** [comment]
> invalidTr_d0g0v0_Shanghai

should fail because we send a tx with `gas_limit=1000`, but the tx passes
