### ISSUE TITLE
bug: LOG_i issues

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/ef-tests#552]
### Current behavior
Any operation involving a LOG_i opcode will try to convert a uint256 into a felt. If the memory byte offset or the memory size are > felt::MAX, this will throw a cairo vm error.

https://github.com/kkrt-labs/kakarot/blob/main/src/kakarot/instructions/logging_operations.cairo#L54

```[tasklist]
### Tasks
- [ ] log2_logMemsizeTooHigh.json
- [ ] log1_logMemsizeTooHigh.json
- [ ] log2_logMemStartTooHigh.json
- [ ] log1_logMemStartTooHigh.json
- [ ] log0_logMemsizeTooHigh.json
- [ ] log4_logMemsizeTooHigh.json
- [ ] log3_logMemsizeTooHigh.json
- [ ] log3_logMemStartTooHigh.json
- [ ] log4_logMemStartTooHigh.json
- [ ] log0_logMemStartTooHigh.json
```
