### ISSUE TITLE
bug: excessif RAM usage causes the process to exit with SIGKILL

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/ef-tests#565]
### Current behavior
The below tests will require excessif RAM in order to run and cause the process to be killed.

```[tasklist]
### Tasks
- [ ] CREATE2_Bounds2.json
- [ ] CALLCODE_Bounds.json
- [ ] CALLCODE_Bounds2.json
- [ ] CALLCODE_Bounds3.json
- [ ] CALLCODE_Bounds4.json
- [ ] CREATE_Bounds.json
- [ ] CREATE_Bounds2.json
- [ ] CREATE_Bounds3.json
- [ ] mload32bitBound_return.json
- [ ] mload32bitBound_return2.json
- [ ] CALL_Bounds.json
- [ ] CALL_Bounds2.json
- [ ] CALL_Bounds2a.json
- [ ] CALL_Bounds3.json
- [ ] DELEGATECALL_Bounds.json
- [ ] DELEGATECALL_Bounds2.json
- [ ] DELEGATECALL_Bounds3.json
- [ ] static_CALL_Bounds.json
- [ ] static_CALL_Bounds2.json
- [ ] static_CALL_Bounds2a.json
- [ ] static_CALL_Bounds3.json
```

**Comment by ClementWalter** [comment]
@greged93 did you investigate this at the time? any insight?

**Comment by greged93** [comment]
No I did not investigate these tests, needs to be verified if these still cause ram issues
