### ISSUE TITLE
bug: false positives tests

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/ef-tests#566]
### Current behavior
The following tests are marked as passed in the ef-tests but are considered false positives, because the passing is due to a crash of the Cairo-vm.

```[tasklist]
### Tasks
- [ ] CREATE2_Bounds3.json -> errors with "Vector capacity exceeded"
- [ ] CREATE2_Bounds.json -> errors with "Could not reach the end of the program. RunResources has no remaining steps."
- [ ] create2collisionSelfdestructedOOG.json -> errors with "Wrong dict pointer supplied. Got 53:9, expected 53:6"
- [ ] create2collisionSelfdestructedRevert.json -> errors with "Wrong dict pointer supplied. Got 53:9, expected 53:6"
```
