### ISSUE TITLE
epic: integrate more tests into the ef-tests repository

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/ef-tests#600]
### Describe the Feature Request

We need to test many things for Kakarot,
The most important part is the EF ethereum-tests, but we also have end-to-end tests, a forge project, and a few data analysis tests (resources job)

```[tasklist]
### Tasks
- [ ] Rename the ef-tests repository into ethereum-tests
- [ ] ef-tests becomes one package of this repository 
- [ ] move the forge project from kakarot 0 to here
- [ ] move the end to end tests project from kakarot 0 to here
- [ ] move the check resources python script from kakarot 0 to here
- [ ] update the CI of Kakarot 0 to run the e2e tests by running them remotely on this repo -> in the same way as ef-tests!
- [ ] update the CI of kakarot 0 to run the check resources by running them remotely on this repo -> in the same way as ef-tests!
- [ ] This repository should now have 3 projects: ef-tests, e2e-tests, data-analysis
- [ ] The language dependencies are Rust, and Python -> update the readme
- [ ] The package dependency includes Forge -> update the readme 
- [ ] Update the make file to be able to run all those different projects separately
```
