### ISSUE TITLE
bug: RunResources has no remaining steps.

### ISSUE THREAD

**Issue by greged93** [kkrt-labs/ef-tests#605]
### Current behavior
The below tests pass but emit a Cairo-vm error with `RunResources has no remaining steps.`

### Expected behavior
Tests should not throw Cairo-vm errors.

```[tasklist]
### Tasks
- [ ] loopExp_d8g0v0_Shanghai
- [ ] loopExp_d12g0v0_Shanghai
- [ ] loopExp_d13g0v0_Shanghai
- [ ] bufferSrcOffset_d108g0v0_Shanghai
- [ ] bufferSrcOffset_d107g0v0_Shanghai
- [ ] bufferSrcOffset_d27g0v0_Shanghai
- [ ] bufferSrcOffset_d11g0v0_Shanghai
- [ ] bufferSrcOffset_d3g0v0_Shanghai
- [ ] bufferSrcOffset_d35g0v0_Shanghai
- [ ] bufferSrcOffset_d59g0v0_Shanghai
- [ ] bufferSrcOffset_d31g0v0_Shanghai
- [ ] bufferSrcOffset_d55g0v0_Shanghai
- [ ] bufferSrcOffset_d51g0v0_Shanghai
- [ ] bufferSrcOffset_d75g0v0_Shanghai
- [ ] buffer_d5g0v0_Shanghai
- [ ] bufferSrcOffset_d79g0v0_Shanghai
- [ ] bufferSrcOffset_d7g0v0_Shanghai
- [ ] bufferSrcOffset_d99g0v0_Shanghai
- [ ] buffer_d95g0v0_Shanghai
- [ ] buffer_d200g0v0_Shanghai
- [ ] buffer_d203g0v0_Shanghai
- [ ] buffer_d21g0v0_Shanghai
- [ ] buffer_d233g0v0_Shanghai
- [ ] buffer_d230g0v0_Shanghai
- [ ] buffer_d263g0v0_Shanghai
- [ ] buffer_d260g0v0_Shanghai
- [ ] CREATE_ContractRETURNBigOffset_d3g0v0_Shanghai
- [ ] buffer_d308g0v0_Shanghai
- [ ] buffer_d305g0v0_Shanghai
- [ ] buffer_d33g0v0_Shanghai
- [ ] buffer_d48g0v0_Shanghai
- [ ] buffer_d36g0v0_Shanghai
- [ ] buffer_d51g0v0_Shanghai
- [ ] buffer_d66g0v0_Shanghai
- [ ] buffer_d63g0v0_Shanghai
- [ ] buffer_d78g0v0_Shanghai
- [ ] buffer_d81g0v0_Shanghai
- [ ] randomStatetest393_d0g0v0_Shanghai
- [ ] CALLBlake2f_d9g2v0_Shanghai
- [ ] CALLBlake2f_d9g3v0_Shanghai
- [ ] CALLCODEBlake2f_d9g1v0_Shanghai
- [ ] CALLCODEBlake2f_d9g2v0_Shanghai
- [ ] CALLCODEBlake2f_d9g3v0_Shanghai
- [ ] randomStatetest443_d0g0v0_Shanghai
- [ ] Call20KbytesContract50_3_d0g0v0_Shanghai
- [ ] randomStatetest133_d0g0v0_Shanghai
- [ ] Call50000_rip160_d0g0v0_Shanghai
- [ ] randomStatetest499_d0g0v0_Shanghai
- [ ] randomStatetest295_d0g0v0_Shanghai
- [ ] randomStatetest601_d0g0v0_Shanghai
- [ ] Call50000_identity2_d0g1v0_Shanghai
- [ ] Call50000_identity2_d0g0v0_Shanghai
- [ ] returndatacopy_overrun_d0g0v0_Shanghai
- [ ] RevertOpcodeReturn_d2g0v0_Shanghai
- [ ] Call50000_d0g1v0_Shanghai
- [ ] Call50000_identity_d0g0v0_Shanghai
- [ ] Call50000_identity_d0g1v0_Shanghai
- [ ] Return50000_d0g0v0_Shanghai
- [ ] Call50000_sha256_d0g1v0_Shanghai
- [ ] Callcode50000_d0g0v0_Shanghai
- [ ] Call50000_ecrec_d0g1v0_Shanghai
- [ ] Return50000_2_d0g0v0_Shanghai
- [ ] Call50000_ecrec_d0g0v0_Shanghai
- [ ] Callcode50000_d0g1v0_Shanghai
- [ ] randomStatetest643_d0g0v0_Shanghai
- [ ] returndatacopy_initial_big_sum_d0g0v0_Shanghai
- [ ] randomStatetest177_d0g0v0_Shanghai
- [ ] failed_tx_xcf416c53_d0g0v0_Shanghai
```
