### ISSUE TITLE
feat: support Cancun migration

### ISSUE THREAD

**Issue by enitrat** [kkrt-labs/ef-tests#676]
## Feature Request

In the [last release](https://github.com/ethereum/tests/releases/tag/v13.1) of the test suite, Pyspec tests folder moved from `/src/BlockchainTestsFiller/Pyspecs` to `/src/GeneralStateTestsFiller/Pyspecs`. As such, they are now comprised in our test generation component which reads tests from the `GeneralState` directory.

However, this is not compatible with the way our runner works for a few reasons:
1. The generated functions from these tests are not formatted as `test_name_dxgxvx_ForkName`, but as `test_src/GeneralStateTestsFillerFiller/Pyspecs/berlin/eip2930_access_list/test_acl.py::test_access_list[fork_Cancun_minus_blockchain_test]()` which is not a valide name for a rust function. As such, we must think of a strategy to adapt these tests.

2. These .py tests now can have both state and blockchain tests. (Not sure yet if we need to run both)

3. (might be related to 2.) Among the generated `.json` files from python specification, some of them are present in `BlockchainTests/GeneralStateTests/Pyspects/cancun/test_folder/test_name.json` but not in `

4. These Pyspec tests might be duplicated from some other tests - for example, `crates/ef-testing/ethereum-tests/src/BlockchainTestsFiller/Pyspecs/shanghai/eip3855_push0/test_push0.py` is a duplicate of `src/GeneralStateTestsFiller/VMTests/vmTests/push0Filler.yml`. Considering this, we must evaluate the need to run the tests generated from the python specification. If it is not required, we can simply skip them.

One of these tests is `crates/ef-testing/ethereum-tests/BlockchainTests/GeneralStateTests/Pyspecs/cancun/eip4788_beacon_root/multi_block_beacon_root_timestamp_calls.json`, which doesn't exist under `crates/ef-testing/ethereum-tests/GeneralStateTests/Pyspecs/cancun/eip4788_beacon_root`. As such, the `secret_key` function fails.

https://github.com/kkrt-labs/ef-tests/blob/6fefabc997a434733e6fa915957ea02e8fcd872c/crates/build-utils/src/content_reader.rs#L25-L37

- [ ] #681
- [ ] #682
- [x] #683
```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/ef-tests/issues/683
- [ ] https://github.com/kkrt-labs/ef-tests/issues/682
- [ ] https://github.com/kkrt-labs/ef-tests/issues/681
- [ ] https://github.com/kkrt-labs/ef-tests/issues/684
```
