### ISSUE TITLE
dev: create documentation for the 3 roles for the ef-test track

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/ef-tests#83]
3 roles: protocolor, debuggor, implementor

Protocolor only creates a test suite, skips failing tests, and create an issue with failing msg in ef-tests

Debuggor figures out the bug, and then creates issue on KKT 0

implementor fixes evm

```[tasklist]
### Tasks
- [x] Create a contributing.md file if it does not exist
- [x] Describe each role precisely
- [x] Create labels that correspond to each role
- [ ] Create issues for the all the test suites
```
