### ISSUE TITLE
epic: add `stSolidityTest` to the blockchain_tests module 

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/ef-tests#86]
# Feature Request

**Describe the Feature Request**

```[tasklist]
### Tasks
- [x] Add the stSolidityTest to the blockchain_tests module in https://github.com/kkrt-labs/ef-tests/blob/6b82c723fb123df8ef3dbc9d5efd21843e005a24/crates/ef-testing/tests/tests.rs#L59
- [x] Run the ef-tests, create issues for each different error messages gotten from test failures. Do not investigate bugs, yet. These issues should have the label "debuggor".
- [ ] Add to the skip matches! macro the name of the tests that fail in https://github.com/kkrt-labs/ef-tests/blob/6b82c723fb123df8ef3dbc9d5efd21843e005a24/crates/ef-testing/src/models/case.rs#L67
- [ ] Later, debuggor labeled issues will handle the investigation of each as they're investigation tasks meant to understand the underlying bug.
```

```[tasklist]
### Linked debuggor issues
- [ ] Add here the 'debuggor' issues resulting from adding the new test suite
- [ ] https://github.com/kkrt-labs/ef-tests/issues/132
- [ ] https://github.com/kkrt-labs/ef-tests/issues/133
- [ ] https://github.com/kkrt-labs/ef-tests/issues/134
- [ ] https://github.com/kkrt-labs/ef-tests/issues/135
- [ ] https://github.com/kkrt-labs/ef-tests/issues/136
- [ ] https://github.com/kkrt-labs/ef-tests/issues/140
- [ ] https://github.com/kkrt-labs/ef-tests/issues/137
- [ ] https://github.com/kkrt-labs/ef-tests/issues/141
- [ ] https://github.com/kkrt-labs/ef-tests/issues/139
- [ ] https://github.com/kkrt-labs/ef-tests/issues/138
```
