### ISSUE TITLE
epic: add `stArgsZeroOneBalance`

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/ef-tests#88]
# Feature Request

**Describe the Feature Request**

```[tasklist]
### Tasks
- [ ] Add the test suite in: https://github.com/kkrt-labs/ef-tests/blob/6b82c723fb123df8ef3dbc9d5efd21843e005a24/crates/ef-testing/tests/tests.rs#L59
- [ ] Run the ef tests `make ef-tests`
- [ ] See which tests are failing if any, create issues for each unique error message which their test linked (include screenshots, code snippets). Refrain from debugging at this point. This is an integration task.
- [ ] If some tests fail, skip them https://github.com/kkrt-labs/ef-tests/blob/6b82c723fb123df8ef3dbc9d5efd21843e005a24/crates/ef-testing/src/models/case.rs#L67
- [ ] you're done
``` 

```[tasklist]
### Linked debuggor issues
- [ ] https://github.com/kkrt-labs/ef-tests/issues/368
- [ ] https://github.com/kkrt-labs/ef-tests/issues/370
- [ ] https://github.com/kkrt-labs/ef-tests/issues/371
```

**Comment by TAdev0** [comment]
@Eikix  hi, 
may i be assigned to this one?

**Comment by TAdev0** [comment]
```[Tasklist]
### Linked debuggor issues
- [ ] #368 
- [ ] #370 
- [ ] #371 
```
