### ISSUE TITLE
epic: add `stBadOpcode`

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/ef-tests#89]
# Feature Request

**Describe the Feature Request**

```[tasklist]
### Tasks
- [x] Add the `stBadOpcode` test suite in: https://github.com/kkrt-labs/ef-tests/blob/6b82c723fb123df8ef3dbc9d5efd21843e005a24/crates/ef-testing/tests/tests.rs#L59
- [x] Run the ef tests `make ef-tests`
- [x] See which tests are failing if any, create issues for each unique error message which their test linked (include screenshots, code snippets). Refrain from debugging at this point. This is an integration task.
- [x] If some tests fail, skip them https://github.com/kkrt-labs/ef-tests/blob/6b82c723fb123df8ef3dbc9d5efd21843e005a24/crates/ef-testing/src/models/case.rs#L67
- [x] you're done, now add these issues down below to the linked debuggor issues tasklist for observability
```

```[tasklist]
### Linked debuggor issues
- [x] Add here the 'debuggor' issues resulting from adding the new test suite
- [ ] https://github.com/kkrt-labs/ef-tests/issues/121
- [ ] https://github.com/kkrt-labs/ef-tests/issues/120
- [ ] https://github.com/kkrt-labs/ef-tests/issues/122
- [ ] https://github.com/kkrt-labs/ef-tests/issues/123
- [ ] https://github.com/kkrt-labs/ef-tests/issues/124
- [ ] https://github.com/kkrt-labs/ef-tests/issues/125
- [ ] https://github.com/kkrt-labs/ef-tests/issues/126
```
