### ISSUE TITLE
epic: add CREATE-related test suite to blockchain tests module

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/ef-tests#90]
# Feature Request

**Describe the Feature Request**

Inside the BlockchainTests > GeneralStateTests, integrate `stCreate2` and `stCreateTest`

```[tasklist]
### Tasks
- [x] Add the `stCreate2` and `stCreateTest` test suites in: https://github.com/kkrt-labs/ef-tests/blob/6b82c723fb123df8ef3dbc9d5efd21843e005a24/crates/ef-testing/tests/tests.rs#L59
- [x] Run the ef tests `make ef-tests`
- [x] See which tests are failing if any, create issues for each unique error message which their test linked (include screenshots, code snippets). Refrain from debugging at this point. This is an integration task.
- [x] If some tests fail, skip them https://github.com/kkrt-labs/ef-tests/blob/6b82c723fb123df8ef3dbc9d5efd21843e005a24/crates/ef-testing/src/models/case.rs#L67
- [x] you're done, now add these issues down below to the linked debuggor issues tasklist for observability
```

```[tasklist]
### Linked debuggor issues
- [ ] https://github.com/kkrt-labs/ef-tests/issues/334
- [ ] https://github.com/kkrt-labs/ef-tests/issues/335
- [ ] https://github.com/kkrt-labs/ef-tests/issues/336
- [ ] https://github.com/kkrt-labs/ef-tests/issues/337
- [ ] https://github.com/kkrt-labs/ef-tests/issues/338
- [ ] https://github.com/kkrt-labs/ef-tests/issues/339
- [ ] https://github.com/kkrt-labs/ef-tests/issues/340
```
