### ISSUE TITLE
epic: add `stCodeCopyTest` and `stCodeSizeLimit`

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/ef-tests#91]
# Feature Request

**Describe the Feature Request**

Inside the BlockchainTests > GeneralStateTests > add `stCodeCopyTest` and `stCodeSizeLimit` to the test suite

```[tasklist]
### Tasks
- [x] Add `stCodeCopyTest` and `stCodeSizeLimit` to the test suite in: https://github.com/kkrt-labs/ef-tests/blob/6b82c723fb123df8ef3dbc9d5efd21843e005a24/crates/ef-testing/tests/tests.rs#L59
- [x] Run the ef tests `make ef-tests`
- [x] See which tests are failing if any, create issues (label them as debuggor) for each unique error message which their test linked (include screenshots, code snippets). Refrain from debugging at this point. This is an integration task.
- [x] If some tests fail, skip them https://github.com/kkrt-labs/ef-tests/blob/6b82c723fb123df8ef3dbc9d5efd21843e005a24/crates/ef-testing/src/models/case.rs#L67
- [x] you're done, now add these issues down below to the linked debuggor issues tasklist for observability
```

```[tasklist]
### Linked debuggor issues
- [ ] https://github.com/kkrt-labs/ef-tests/issues/262
- [ ] https://github.com/kkrt-labs/ef-tests/issues/263
- [ ] https://github.com/kkrt-labs/ef-tests/issues/264
- [ ] https://github.com/kkrt-labs/ef-tests/issues/265
```

**Comment by khaeljy** [comment]
Can I get this one pls?
