### ISSUE TITLE
feat: add `stChainId` to the blockchain tests module

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/ef-tests#92]
# Feature Request

**Describe the Feature Request**

Inside the BlockchainTests > GeneralStateTests > add `stChainId` to the blockchain tests module

```[tasklist]
### Tasks
- [ ] Add the `stChainId` to the test suite in: https://github.com/kkrt-labs/ef-tests/blob/6b82c723fb123df8ef3dbc9d5efd21843e005a24/crates/ef-testing/tests/tests.rs#L59
- [ ] Run the ef tests `make ef-tests`
- [ ] See which tests are failing if any, create issues (label them as debuggor) for each unique error message which their test linked (include screenshots, code snippets). Refrain from debugging at this point. This is an integration task.
- [ ] If some tests fail, skip them https://github.com/kkrt-labs/ef-tests/blob/6b82c723fb123df8ef3dbc9d5efd21843e005a24/crates/ef-testing/src/models/case.rs#L67
- [ ] you're done
```
