### ISSUE TITLE
epic: add `stLogTests` to the blockchain tests module

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/ef-tests#93]
# Feature Request

**Describe the Feature Request**

Inside the BlockchainTests > GeneralStateTests >  add `stLogTests` to the blockchain tests module

```[tasklist]
### Tasks
- [x] Add the `stLogTests` test suite in: https://github.com/kkrt-labs/ef-tests/blob/6b82c723fb123df8ef3dbc9d5efd21843e005a24/crates/ef-testing/tests/tests.rs#L59
- [x] Run the ef tests `make ef-tests`
- [x] See which tests are failing if any, create issues (label them `debuggor`) for each unique error message which their test linked (include screenshots, code snippets). Refrain from debugging at this point. This is an integration task.
- [x] If some tests fail, skip them https://github.com/kkrt-labs/ef-tests/blob/6b82c723fb123df8ef3dbc9d5efd21843e005a24/crates/ef-testing/src/models/case.rs#L67
- [x] you're done
```

```[tasklist]
### Linked debuggor issues
- [x] Add here the 'debuggor' issues resulting from adding the new test suite
```

**Comment by TAdev0** [comment]
#513
