### ISSUE TITLE
epic: add `stInitCodeTest` to the blockchain tests module 

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/ef-tests#94]
# Feature Request

**Describe the Feature Request**

Inside the BlockchainTests > GeneralStateTests >  add `stInitCodeTest` to the blockchain tests module

```[tasklist]
### Tasks
- [ ] Add the `stInitCodeTest` test suite in: https://github.com/kkrt-labs/ef-tests/blob/6b82c723fb123df8ef3dbc9d5efd21843e005a24/crates/ef-testing/tests/tests.rs#L59
- [ ] Run the ef tests `make ef-tests`
- [ ] See which tests are failing if any, create issues (label them `debuggor`) for each unique error message which their test linked (include screenshots, code snippets). Refrain from debugging at this point. This is an integration task.
- [ ] If some tests fail, skip them https://github.com/kkrt-labs/ef-tests/blob/6b82c723fb123df8ef3dbc9d5efd21843e005a24/crates/ef-testing/src/models/case.rs#L67
- [ ] you're done, now add these issues down below to the linked debuggor issues tasklist for observability
```

```[tasklist]
### Linked debuggor issues
- [ ] Add here the 'debuggor' issues resulting from adding the new test suite
```

```[tasklist]
### Tasks
- [ ] https://github.com/kkrt-labs/ef-tests/issues/108
- [ ] https://github.com/kkrt-labs/ef-tests/issues/109
- [ ] https://github.com/kkrt-labs/ef-tests/issues/110
- [ ] https://github.com/kkrt-labs/ef-tests/issues/111
- [ ] https://github.com/kkrt-labs/ef-tests/issues/112
- [ ] https://github.com/kkrt-labs/ef-tests/issues/113
- [ ] https://github.com/kkrt-labs/ef-tests/issues/114
- [ ] https://github.com/kkrt-labs/ef-tests/issues/115
- [ ] https://github.com/kkrt-labs/ef-tests/issues/116
- [ ] https://github.com/kkrt-labs/ef-tests/issues/117
```
