### ISSUE TITLE
epic: add `stExtCodeHash` to the blockchain tests module

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/ef-tests#95]
# Feature Request

**Describe the Feature Request**

Inside the BlockchainTests > GeneralStateTests >  add `stExtCodeHash` to the blockchain tests module

```[tasklist]
### Tasks
- [x] Add the `stExtCodeHash` test suite in: https://github.com/kkrt-labs/ef-tests/blob/6b82c723fb123df8ef3dbc9d5efd21843e005a24/crates/ef-testing/tests/tests.rs#L59
- [x] Run the ef tests `make ef-tests`
- [x] See which tests are failing if any, create issues (label them `debuggor`) for each unique error message which their test linked (include screenshots, code snippets). Refrain from debugging at this point. This is an integration task.
- [x] If some tests fail, skip them https://github.com/kkrt-labs/ef-tests/blob/6b82c723fb123df8ef3dbc9d5efd21843e005a24/crates/ef-testing/src/models/case.rs#L67
- [x] you're done, now add these issues down below to the linked debuggor issues tasklist for observability
```

```[tasklist]
### Linked debuggor issues
- [ ] Add here the 'debuggor' issues resulting from adding the new test suite
- [ ] https://github.com/kkrt-labs/ef-tests/issues/270
- [ ] https://github.com/kkrt-labs/ef-tests/issues/271
- [ ] https://github.com/kkrt-labs/ef-tests/issues/272
- [ ] https://github.com/kkrt-labs/ef-tests/issues/273
- [ ] https://github.com/kkrt-labs/ef-tests/issues/274
- [ ] https://github.com/kkrt-labs/ef-tests/issues/275
- [ ] https://github.com/kkrt-labs/ef-tests/issues/276
- [ ] https://github.com/kkrt-labs/ef-tests/issues/277
- [ ] https://github.com/kkrt-labs/ef-tests/issues/278
- [ ] https://github.com/kkrt-labs/ef-tests/issues/279
- [ ] https://github.com/kkrt-labs/ef-tests/issues/280
- [ ] https://github.com/kkrt-labs/ef-tests/issues/281
- [ ] https://github.com/kkrt-labs/ef-tests/issues/282
- [ ] https://github.com/kkrt-labs/ef-tests/issues/283
- [ ] https://github.com/kkrt-labs/ef-tests/issues/284
- [ ] https://github.com/kkrt-labs/ef-tests/issues/285
- [ ] https://github.com/kkrt-labs/ef-tests/issues/286
- [ ] https://github.com/kkrt-labs/ef-tests/issues/287
- [ ] https://github.com/kkrt-labs/ef-tests/issues/288
- [ ] https://github.com/kkrt-labs/ef-tests/issues/289
- [ ] https://github.com/kkrt-labs/ef-tests/issues/290
- [ ] https://github.com/kkrt-labs/ef-tests/issues/291
- [ ] https://github.com/kkrt-labs/ef-tests/issues/512
```

**Comment by danilowhk** [comment]
I will take this one

**Comment by TAdev0** [comment]
#512
